/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package API;

import org.junit.Test;
import static org.junit.Assert.*;

public class DBControllerTest {
    /*@Test public void testAppHasAGreeting() {
        DBController classUnderTest = new DBController();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }*/
}
